[package]
name = "postgres-ical-parser"
version = "0.0.0"
description = "One day, this will be its own crate"
edition = "2018"
publish = false

[dependencies]
chrono = "0.4.40"
chrono-tz = "0.10.3"
ical = "0.11.0"
log = "0.4.27"
thiserror = "2.0"
