name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    container: rust:1.58.1-alpine
    steps:
      - uses: actions/checkout@v2
      - name: cargo test
        run: cargo test --package postgres-ical-parser --package postgres-ical
  build:
    runs-on: ubuntu-latest
    container: timescaledev/rust-pgx
    steps:
    - uses: actions/checkout@v2
    - name: pgx package
      run: cargo pgx package
